config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :projects
  resources :projects do
    resources :tasks

    resources :tasks do
      resources :posts
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :task
  validates :titulo, presence: {message: 'o campo é obrigatório.'},
                      length: { minimum: 2, maximum: 60, 
                                too_short: "%{count} é o número mínimo de caracteres para o campo", 
                                too_long: "%{count} é o número máximo de caracteres para o campo"
                              }
  validates :texto, presence: {message: 'o campo é obrigatório.'}
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :status
  has_many :task, dependent: :destroy
  validates :nome, presence: {message: "o campo é obrigatório."}, 
                   length: { minimum: 2, maximum: 60, 
                             too_short: "%{count} é o número mínimo de caracteres para o campo", 
                             too_long: "%{count} é o número máximo de caracteres para o campo"
                            }

  validates :descricao, presence: {message: "o campo é de preenchimento obrigatório."}
end 

app/models/status.rb
class Status < ApplicationRecord
  has_many :project
  self.table_name = "status"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :posts, dependent: :destroy
  validates :nome, presence: {message: "o campo é obrigatório."}, 
                    length: { minimum: 2, maximum: 60, 
                      too_short: "%{count} é o número mínimo de caracteres para o campo", 
                      too_long: "%{count} é o número máximo de caracteres para o campo"
                    }
  validates :descricao, presence: {message: "o campo é de preenchimento obrigatório."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_task
  before_action :set_project

  def index
  end

  def show
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post atualizado com sucesso"
      @project = @task.project
      redirect_to project_task_path(@project, @task)
    else
      render 'edit'
    end
  end

  def create
    @post = Post.new(post_params)
    @post.task = @task

    if @post.save
      flash[:notice] = "Post Criado com sucesso."
      @project = @task.project
      redirect_to project_task_path(@project, @task)
    else
      render 'new'
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Post excluído com sucesso."
      redirect_to project_task_path(@project, @task)
    else
      render 'index'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def post_params
    params.require(:post).permit(:titulo, :texto)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :show, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Projeto criado com sucesso."
      redirect_to @project
     else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Projeto Atualizado com sucesso."
      redirect_to @project
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if @project.destroy
      flash[:notice] = "Projeto Excluído com sucesso."
      redirect_to projects_path
    else
      render projects_path
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    parameters = params.require(:project).permit(:nome, :descricao, :github_url, :status_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  def index
    @tasks = @project.task
  end

  def show
  end

  def create
    @task = Task.new(task_params)
    @task.project = @project
    if @task.save
      flash[:notice] = "Tarefa criada com sucesso."
      redirect_to project_task_path(@project, @task)
    else
      render 'new'
    end
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = "Tarefa atualizada com sucesso."
      redirect_to project_task_path(@project, @task)
    else
      render 'edit'
    end
  end

  def destroy
    if @task.destroy
      flash[:notice] = "Tarefa Excluída com sucesso."
      redirect_to project_path(@project)
    else
      render 'index'
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    parameters = params.require(:task).permit(:nome, :status_id, :descricao, :commit_hash)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
  <footer id="sticky-footer" class="flex-shrink-0 py-2 h-10 bg-dark text-white-50 mt-6">
    <div class="container text-center text-decoration-none">
      <small>
        Copyright &copy; 
        <%= link_to 'Murilo Ávila', 'https://www.linkedin.com/in/murilo-avila-117a3592/', class: 'text-decoration-none text-white-50' %>
        <%= link_to image_tag("github-11-24.png"), 'https://github.com/muriloavila'%>
      </small>
    </div>
  </footer>

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark navigation">
  <div class="container-fluid">
    <%= link_to 'Jupiter', root_path, class: 'navbar-brand', style: 'font-size:2.00rem' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      </ul>
      <a class="navbar-brand btn btn-dark border border-white" href="#">Sign in</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jupiter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-dark text-white body">
    <%= render 'layouts/navigation' %>
    <div class="container col-8 justify-content-md-center">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bem vindo</h1>

<%= render @projects %>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<%= form_with(model: @post, local: true, url: project_task_posts_path) do |form| %>
  <%= form.label :titulo, 'Título' %><br />
  <%= form.text_field :titulo %><br /><br />
  <%= form.text_area :texto %><br />
  <%= form.submit %>
<% end %>

app/views/posts/_post.html.erb
<%= link_to project_task_post_path(@project, @task, post), class: 'text-decoration-none',action: 'go' do %>
<div class="py-2">
  <div class="card text-white bg-dark mb-3 rounded-3 border-secondary">
    <div class="card-header text-center rounded-3">
      <h5 class="card-title text-white"><%= post.titulo %></h5>
    </div>
    <div class="card-body rounded-3" style="height: 100px">
      <p class="card-text" style="font-size: 16px"> <%= post.texto.first(300)  %><%= '...' if post.texto.length > 300 %> </p>
    </div>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editar Post</h1>
<%= render 'shared/errors', obj: @post %>

<%= form_with(model: @post, local: true, url: project_task_post_path(@project, @task, @post), method: 'PATCH') do |form| %>
  <%= form.label :titulo, 'Título' %><br />
  <%= form.text_field :titulo %><br /><br />
  <%= form.text_area :texto %><br />
  <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<%= render 'shared/errors', obj: @post %>

<h1> <%= @task.nome %> Posts </h1>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1> <%= @post.titulo %> </h1>

<p><%= @post.texto %></p>

<%= link_to 'Editar', edit_project_task_post_path(@project, @task, @post) %>
<%= link_to 'Deletar', project_task_post_path(@project, @task, @post), method: :delete %>

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>

<div>
  <%= form_with(model: @project, local: true) do |form| %>
    <%= form.label :nome, "Nome: " %>
    <%= form.text_field :nome %><br />
    <%= form.label :descricao, "Descrição: " %>
    <%= form.text_area :descricao %><br />
    <%= form.label :github_url, "Github: " %>
    <%= form.text_field :github_url %><br />
    <%= form.label :status, "Status: " %>
    <%= form.collection_select(:status_id, Status.order('nome_status'), :id, :nome_status, {prompt: "-- Status --"}) %><br />
    <%= form.submit %>
  <% end %>
</div>

app/views/projects/_project.html.erb
<p> 
  <%= link_to project.nome, project %> | <%= link_to 'Deletar', project, method: :delete %>
</p>

app/views/projects/edit.html.erb
<h1>Projeto</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= render 'layouts/message' %>
<h1>Projetos</h1>

<%= render @projects %>

app/views/projects/new.html.erb
<h1>Novo Projeto</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="h-100 pt-5 pb-2 text-white bg-transparent">
  <%= render 'layouts/message' %>
  <p style="padding-bottom: 0px;font-family: Roboto;font-size: 45px;font-weight: 300;">
    <span><%= @project.nome %></span>
    <span><%= link_to image_tag("GitHub-Mark-Light-32px.png"), @project.github_url %></span>
  </p>

  <p style="padding-bottom: 0px;font-size: 15px;font-weight: 300;"><%= @project.descricao %></p>
  
  <div style="text-align: right">
    <%= link_to 'Criar Nova Tarefa', new_project_task_path(@project), class: 'btn btn-dark border border-white text-right' %>
  </div>
</div>

<hr>
<%= render @project.task %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'shared/errors', obj: @task %>


<%= form_with(model: @task, local: true, url: project_tasks_path) do |form| %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :nome, 'Título:' %>
      <%= form.text_field :nome, class: 'form-control form-control-sm' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :status_id, 'Status:' %>
      <%= form.collection_select(:status_id, Status.all, :id, :nome_status, {prompt: "-- Status --"}, {class: 'form-control form-control-sm text-center'}) %>
    </div>
    <div class="form-group">
      <%= form.label :commit_hash, 'Hash Commit:' %>
      <%= form.text_field :commit_hash, class: 'form-control form-control-sm' %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :descricao, 'Descrição:' %>
    <%= form.text_area :descricao, class: 'form-control form-control-sm', rows: '7' %>
  </div>
  <div class="form-group text-center">
    <%= form.submit 'Criar Tarefa', class: 'mt-4 btn btn-dark border border-white' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= link_to project_task_path(@project, task), class: 'text-decoration-none',action: 'go' do %>
<div class="card bg-dark mt-2 border-secondary rounded-3 text-white">
  <div class="card-body rounded-3">
    <h5 class="card-title" style="font-weight: bold"><%= task.nome %></h5>
    <p class="card-text"><%= task.descricao %></p>
    <h6 class="card-subtitle mb-2 text-muted" style="font-size: 12px;"><%= task.created_at.strftime("%d/%m/%Y %H:%M:%S") %></h6>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container col-8 mt-4">
  <h1 class="text-center title">Editar Tarefa</h1>

  <%= render 'shared/errors', obj: @task %>

  <%= form_with(model: @task, local: true, url: project_task_path(@project, @task), method: 'PATCH') do |form| %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :nome, 'Título:' %>
        <%= form.text_field :nome, class: 'form-control form-control-sm' %>
      </div>
      <div class="form-group col-md-6">
        <%= form.label :status_id, 'Status:' %>
        <%= form.collection_select(:status_id, Status.all, :id, :nome_status, {prompt: "-- Status --"}, {class: 'form-control form-control-sm text-center'}) %>
      </div>
      <div class="form-group">
        <%= form.label :commit_hash, 'Hash Commit:' %>
        <%= form.text_field :commit_hash, class: 'form-control form-control-sm' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :descricao, 'Descrição:' %>
      <%= form.text_area :descricao, class: 'form-control form-control-sm', rows: '7' %>
    </div>
    <div class="form-group text-center">
      <%= form.submit 'Atualizar Tarefa', class: 'mt-4 btn btn-dark border border-white' %>
    </div>
  <% end %>

</div>

app/views/tasks/index.html.erb
<h1>Tarefas</h1>

<%= render @tasks %>

app/views/tasks/new.html.erb
<div class="container col-8 mt-4">
  <h1 class="text-center title">Nova Tarefa</h1>
  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class="container py-5">
  <%= render 'layouts/message' %>

  <p style="padding-bottom: 0px;font-family: Roboto;font-size: 45px;font-weight: 300;">
    <%= @task.nome %>
  </p>

  <p style="padding-bottom: 0px;font-size: 15px;font-weight: 300;font-family: Roboto;"><%= @task.descricao %></p>

  <%= link_to 'Editar', edit_project_task_path(@project, @task) %>
  <%= link_to 'Deletar', project_task_path(@project, @task), method: :delete %>

  <hr>

  <%= render @task.posts %>
</div>